server:
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:ideantify}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 5
  sql:
    init:
      mode: always
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client-name: Kakao
            redirect-uri: ${KAKAO_REDIRECT_URI:http://localhost:8080/api/login/oauth2/code/kakao}
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
app:
  jwt:
    key: ${JWT_SECRET_KEY:dummySecretKeyForDevelopment1234567890abcdefghijklmnopqrstuvwxyz}
  auth:
    oauth:
      callback:
        google: ${GOOGLE_CALLBACK_URL:http://localhost:3000/auth/callback}
        kakao: ${KAKAO_CALLBACK_URL:http://localhost:3000/auth/callback}
#logging:
#  level:
#    org.springframework.security: TRACE
#    org.springframework.security.oauth2: TRACE
#    org.springframework.web.client.RestTemplate: DEBUG
#    org.apache.http: DEBUG
aws:
  sqs:
    enabled: ${AWS_SQS_ENABLED:true}
spring.cloud:
  aws:
    region:
      static: ${AWS_REGION:ap-northeast-2}
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    sqs:
      queue:
        ai-request: ${AWS_SQS_AI_REQUEST_QUEUE_URL}
        ai-response: ${AWS_SQS_AI_RESPONSE_QUEUE_URL}
